//
//  Model.swift
//  NFTour
//
//  Created by Maria Luiza Amaral on 15/11/21.
//

import Foundation
import UIKit
import CoreLocation

class Model: ObservableObject {

    var profile: ProfileUser = ProfileUser (picture: UIImage(named: "profile")!, user: "@maluzeira", wallet: "0x4265de963cdd60629d03fee2cd3285e6d5ff6015",
                                            
        nfts: [
            NFT(id: UUID().uuidString, image: "opensea_nft", name: "Mystical melt", price: 0.11 , properties: "rare", description: "The most abstract NFT collection of all time! 1000 NFTS are made from a combination of over 200 inks, hand-drawn in a specific color mixing technique. The Mystical Melts are active in the Ethereum blockchain in the form of ERC-721 tokens.", creator: "romeoblaze", linkOpenSea: "https://opensea.io/assets/0x8dd92dd186f05e3e9f1844cd9047617adad8a66d/5486",isPositioned: true, localization: "Avenida das Árvores, Santa Cândida, Curitiba, Brasil", coordinates: CLLocation(latitude: -25.428972014308425, longitude: -49.345491353084)),
            
            NFT(id: UUID().uuidString, image: "nft1", name: "Mystical melt", price: 2.55 , properties: "rare", description: "The most abstract NFT collection of all time! 1000 NFTS are made from a combination of over 200 inks, hand-drawn in a specific color mixing technique. The Mystical Melts are active in the Ethereum blockchain in the form of ERC-721 tokens.", creator: "Florence", linkOpenSea: "https://opensea.io/assets/0xbc4ca0eda7647a8ab7c2061c2e118a18a936f13d/9180",isPositioned: true, localization: "Avenida das Árvores, Santa Cândida, Curitiba, Brasil", coordinates: CLLocation(latitude: -25.41790765, longitude: -49.27141909)),
            
            NFT(id: UUID().uuidString, image: "nft2", name: "Duck",  price: 2.55, properties: "rare", description: "The most abstract NFT collection of all time! 1000 NFTS are made from a combination of over 200 inks, hand-drawn in a specific color mixing technique. The Mystical Melts are active in the Ethereum blockchain in the form of ERC-721 tokens.", creator: "Florence", linkOpenSea: "https://opensea.io/assets/0xbc4ca0eda7647a8ab7c2061c2e118a18a936f13d/9180", isPositioned: true, localization: "Avenida das Árvores, Santa Cândida, Curitiba, Brasil",coordinates: CLLocation(latitude: -25.417920, longitude: -49.271615)),
            
            NFT(id: UUID().uuidString, image: "nft3", name: "Kong", price: 2.55, properties: "rare", description: "The most abstract NFT collection of all time! 1000 NFTS are made from a combination of over 200 inks, hand-drawn in a specific color mixing technique. The Mystical Melts are active in the Ethereum blockchain in the form of ERC-721 tokens.", creator: "Florence", linkOpenSea: "https://opensea.io/assets/0xbc4ca0eda7647a8ab7c2061c2e118a18a936f13d/9180", isPositioned: true, localization: "Avenida das Árvores, Santa Cândida, Curitiba, Brasil",coordinates: CLLocation(latitude: -25.6179076, longitude: -49.3714190)),
            
            NFT(id: UUID().uuidString, image: "nft4", name: "Crazy NFT", price: 2.55, properties: "rare", description: "The most abstract NFT collection of all time! 1000 NFTS are made from a combination of over 200 inks, hand-drawn in a specific color mixing technique. The Mystical Melts are active in the Ethereum blockchain in the form of ERC-721 tokens.", creator: "Florence", linkOpenSea: "https://opensea.io/assets/0xbc4ca0eda7647a8ab7c2061c2e118a18a936f13d/9180", isPositioned: false, localization: "",coordinates: CLLocation(latitude: -25.1170, longitude: -49.169)),
            
            NFT(id: UUID().uuidString, image: "nft5", name: "Mystical melt", price: 2.55, properties: "rare", description: "The most abstract NFT collection of all time! 1000 NFTS are made from a combination of over 200 inks, hand-drawn in a specific color mixing technique. The Mystical Melts are active in the Ethereum blockchain in the form of ERC-721 tokens.", creator: "Florence", linkOpenSea: "https://opensea.io/assets/0xbc4ca0eda7647a8ab7c2061c2e118a18a936f13d/9180", isPositioned: false, localization: "",coordinates: CLLocation(latitude: -25.417907, longitude: -49.27141)),
            
            NFT(id: UUID().uuidString, image: "nft6", name: "Mystical melt", price: 2.55, properties: "rare", description: "The most abstract NFT collection of all time! 1000 NFTS are made from a combination of over 200 inks, hand-drawn in a specific color mixing technique. The Mystical Melts are active in the Ethereum blockchain in the form of ERC-721 tokens.", creator: "Florence", linkOpenSea: "https://opensea.io/assets/0xbc4ca0eda7647a8ab7c2061c2e118a18a936f13d/9180", isPositioned: true, localization: "Avenida das Árvores, Santa Cândida, Curitiba, Brasil",coordinates: CLLocation(latitude: 25.41790765, longitude: 49.27141909)),
            
            NFT(id: UUID().uuidString, image: "nft7", name: "Mystical melt", price: 2.55, properties: "rare", description: "The most abstract NFT collection of all time! 1000 NFTS are made from a combination of over 200 inks, hand-drawn in a specific color mixing technique. The Mystical Melts are active in the Ethereum blockchain in the form of ERC-721 tokens.", creator: "Florence", linkOpenSea: "https://opensea.io/assets/0xbc4ca0eda7647a8ab7c2061c2e118a18a936f13d/9180",isPositioned: false, localization: "",coordinates: CLLocation(latitude: 0, longitude: 0)),
            
            NFT(id: UUID().uuidString, image: "nft8", name: "Mystical melt", price: 2.55, properties: "rare", description: "The most abstract NFT collection of all time! 1000 NFTS are made from a combination of over 200 inks, hand-drawn in a specific color mixing technique. The Mystical Melts are active in the Ethereum blockchain in the form of ERC-721 tokens.", creator: "Florence", linkOpenSea: "https://opensea.io/assets/0xbc4ca0eda7647a8ab7c2061c2e118a18a936f13d/9180", isPositioned: false, localization: "",coordinates: CLLocation(latitude: 0, longitude: 0)),
            
            NFT(id: UUID().uuidString, image: "nft9", name: "Mystical melt", price: 2.55, properties: "rare", description: "The most abstract NFT collection of all time! 1000 NFTS are made from a combination of over 200 inks, hand-drawn in a specific color mixing technique. The Mystical Melts are active in the Ethereum blockchain in the form of ERC-721 tokens.", creator: "Florence", linkOpenSea: "https://opensea.io/assets/0xbc4ca0eda7647a8ab7c2061c2e118a18a936f13d/9180", isPositioned: false, localization: "",coordinates: CLLocation(latitude: 0, longitude: 0)),
            
            NFT(id: UUID().uuidString, image: "nft10", name: "Mystical melt", price: 2.55, properties: "rare", description: "The most abstract NFT collection of all time! 1000 NFTS are made from a combination of over 200 inks, hand-drawn in a specific color mixing technique. The Mystical Melts are active in the Ethereum blockchain in the form of ERC-721 tokens.", creator: "Florence", linkOpenSea: "https://opensea.io/assets/0xbc4ca0eda7647a8ab7c2061c2e118a18a936f13d/9180", isPositioned: false, localization: "",coordinates: CLLocation(latitude: 0, longitude: 0)),
            
            NFT(id: UUID().uuidString, image: "nft11", name: "Mystical melt", price: 2.55, properties: "rare", description: "The most abstract NFT collection of all time! 1000 NFTS are made from a combination of over 200 inks, hand-drawn in a specific color mixing technique. The Mystical Melts are active in the Ethereum blockchain in the form of ERC-721 tokens.", creator: "Florence", linkOpenSea: "https://opensea.io/assets/0xbc4ca0eda7647a8ab7c2061c2e118a18a936f13d/9180", isPositioned: true, localization: "Avenida das Árvores, Santa Cândida, Curitiba, Brasil",coordinates: CLLocation(latitude: 0, longitude: 0)),
            
            NFT(id: UUID().uuidString, image: "nft12", name: "Mystical melt", price: 2.55, properties: "rare", description: "The most abstract NFT collection of all time! 1000 NFTS are made from a combination of over 200 inks, hand-drawn in a specific color mixing technique. The Mystical Melts are active in the Ethereum blockchain in the form of ERC-721 tokens.", creator: "Florence", linkOpenSea: "https://opensea.io/assets/0xbc4ca0eda7647a8ab7c2061c2e118a18a936f13d/9180", isPositioned: false,  localization: "",coordinates: CLLocation(latitude: 0, longitude: 0)),
            
            NFT(id: UUID().uuidString, image: "nft13", name: "Mystical melt", price: 2.55, properties: "rare", description: "The most abstract NFT collection of all time! 1000 NFTS are made from a combination of over 200 inks, hand-drawn in a specific color mixing technique. The Mystical Melts are active in the Ethereum blockchain in the form of ERC-721 tokens.", creator: "Florence", linkOpenSea: "https://opensea.io/assets/0xbc4ca0eda7647a8ab7c2061c2e118a18a936f13d/9180", isPositioned: false, localization: "",coordinates: CLLocation(latitude: 0, longitude: 0)),
            
            NFT(id: UUID().uuidString, image: "nft14", name: "Mystical melt", price: 2.55, properties: "rare", description: "The most abstract NFT collection of all time! 1000 NFTS are made from a combination of over 200 inks, hand-drawn in a specific color mixing technique. The Mystical Melts are active in the Ethereum blockchain in the form of ERC-721 tokens.", creator: "Florence", linkOpenSea: "https://opensea.io/assets/0xbc4ca0eda7647a8ab7c2061c2e118a18a936f13d/9180", isPositioned: true, localization: "Avenida das Árvores, Santa Cândida, Curitiba, Brasil",coordinates: CLLocation(latitude: 0, longitude: 0)),
            
            NFT(id: UUID().uuidString, image: "nft15", name: "Mystical melt", price: 2.55, properties: "rare", description: "The most abstract NFT collection of all time! 1000 NFTS are made from a combination of over 200 inks, hand-drawn in a specific color mixing technique. The Mystical Melts are active in the Ethereum blockchain in the form of ERC-721 tokens.", creator: "Florence", linkOpenSea: "https://opensea.io/assets/0xbc4ca0eda7647a8ab7c2061c2e118a18a936f13d/9180", isPositioned: true, localization: "Avenida das Árvores, Santa Cândida, Curitiba, Brasil",coordinates: CLLocation(latitude: 0, longitude: 0))]
        
        )
}
